spring:
    application:
        name: "mybooks-api"
        title: "MyBooks API"
        description: "MyBooks API"
        version: "1.0"
        author: "ale fuentes"
    # H2 Database Configuration
    datasource:
        url: jdbc:h2:mem:mybooksdb
        username: sa
        password: 
        driverClassName: org.h2.Driver
    # JPA Configuration
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
        user:
            name: admin
            password: admin
            roles: ADMIN
        basic:
            enabled: true

server:
    port: 8081
# H2 Console Configuration
h2:
    console:
        enabled: true
        path: /h2-console
