spring:
    application:
        name: "mybooks-api"
        title: "MyBooks API"
        description: "MyBooks API"
        version: "1.0"
        author: "ale fuentes"
    # H2 Database Configuration
    datasource:
        url: jdbc:postgresql://localhost:5432/booksdb
        username: postgres
        password: postgres
    # JPA Configuration
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    # REDIS Configuration
    redis:
        host: redis
        port: 6379
    # Security Configuration
    security:
        user:
            name: admin
            password: admin
            roles: ADMIN
        basic:
            enabled: true

# Server Configuration
server:
    port: 8081

# H2 Console Configuration
h2:
    console:
        enabled: true
        path: /h2-console
